name: Workflow A

on:
  push:
    branches: [ "master" ]

jobs:
  some_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Some Step 
        run: echo "Hello!"

  job_producing_data:  
    runs-on: ubuntu-latest
    steps:
      - name: Some Step 
        uses: actions/upload-artifact@v3
        with:
          name: new.txt
          
